### ISSUE TITLE
Updating to new folder structure?

### ISSUE THREAD

**Issue by MeckerOpa** [Booster1212/Athena-OSDoorController#4]
Hi, will you update everything to the new folder structure for V3.1.0 ?

**Comment by jonesXYZ** [comment]
Hey, he is already refactoring the old stuff for 3.2.0

**Comment by Booster1212** [comment]
Dev branch already holds new folder structure, since i build it on Vue's Composition API it will take a while until its finished, the Backend is almost done.

**Comment by MeckerOpa** [comment]
Sounds great! Thanks! 
Is there any discord or somewhere else I can communicate and geht some Infos?

**Comment by Booster1212** [comment]
https://discord.gg/zCqZ3XA7E3

> Sounds great! Thanks! Is there any discord or somewhere else I can communicate and geht some Infos?
